# Generated by Django 5.1.4 on 2026-05-31 20:35

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.SlugField(blank=True, help_text='Public handle, e.g. /u/<username>', max_length=30, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('body_fat_pct', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Very active'), ('athlete', 'Athlete')], default='moderate', max_length=20)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight loss'), ('fat_loss', 'Fat loss'), ('lean_bulk', 'Lean bulk'), ('muscle_gain', 'Muscle gain'), ('maintenance', 'Maintenance'), ('recomposition', 'Recomposition')], default='maintenance', max_length=20)),
                ('weekly_training_days', models.PositiveSmallIntegerField(default=3)),
                ('gym_access', models.BooleanField(default=True)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('sleep_average_hours', models.FloatField(default=7.0)),
                ('dietary_preference', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('halal', 'Halal')], default='omnivore', max_length=20)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('tdee', models.FloatField(blank=True, null=True)),
                ('maintenance_calories', models.FloatField(blank=True, null=True)),
                ('recommended_calories', models.FloatField(blank=True, null=True)),
                ('protein_target_g', models.FloatField(blank=True, null=True)),
                ('carbs_target_g', models.FloatField(blank=True, null=True)),
                ('fat_target_g', models.FloatField(blank=True, null=True)),
                ('water_target_ml', models.FloatField(blank=True, null=True)),
                ('sleep_target_hours', models.FloatField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('accent_color', models.CharField(default='#7c5cff', max_length=9)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
